stages:
  - deploy

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # Install SSH and set up ssh-agent
    - apk update && apk add --no-cache openssh sshpass
    - mkdir -p ~/.ssh
    - echo "$HOST_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$HOST_URL" >> ~/.ssh/known_hosts

    # Start ssh-agent and add the private key with the passphrase
    - eval $(ssh-agent -s)
    - echo "$HOST_PASSPHRASE" | ssh-add ~/.ssh/id_rsa
  script:
    - echo "Connecting to VPS..."
    - ssh $VPS_USER@$HOST_URL "
      echo 'Connected to VPS!';
      uname -a;
      uptime;
      "
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
