stages:
  - deploy

deploy:
  stage: deploy
  image: docker:latest # Use the same Docker image
  services:
    - docker:dind # Required for docker commands if needed later
  before_script:
    # Install SSH and set up the environment
    - apk update && apk add --no-cache openssh
    - mkdir -p ~/.ssh                          # Prepare SSH directory
    - echo "$HOST_PRIVATE_KEY" > ~/.ssh/id_rsa # Add the private key from GitLab CI/CD variables
    - chmod 600 ~/.ssh/id_rsa                  # Restrict private key permissions
    - ssh-keyscan -H "$HOST_URL" >> ~/.ssh/known_hosts # Add VPS to known hosts
  script:
    # Connect to the VPS and run simple commands
    - echo "Connecting to VPS..."
    - ssh $VPS_USER@$HOST_URL "
      echo 'Connected to VPS!';
      uname -a;
      uptime;
      "
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"' # Run only on the main branch
