stages:
  - deploy

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind # Service is included in case Docker is needed later
  before_script:
    # Install SSH and ssh-agent
    - apk update && apk add --no-cache openssh sshpass

    # Decode the Base64-encoded private key and save it to ~/.ssh/id_rsa
    - echo "$HOST_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # Ensure proper permissions for the private key

    # Add the VPS host to known_hosts to avoid authenticity confirmation prompts
    - ssh-keyscan -H "$HOST_URL" >> ~/.ssh/known_hosts

    # Start the ssh-agent and add the private key using the passphrase
    - eval $(ssh-agent -s)
    - echo "$HOST_PASSPHRASE" | ssh-add ~/.ssh/id_rsa

  script:
    # Test the connection to the VPS
    - echo "Connecting to VPS..."
    - ssh $VPS_USER@$HOST_URL "
      echo 'Connected to VPS!';
      uname -a;
      uptime;
      "
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"' # Only run on the main branch
