stages:
  - check_and_prepare
  - test
  - build
  - deploy

variables:
  FRONTEND_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/sharednotes-frontend"
  BACKEND_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/sharednotes-backend"
  VERSION: "latest"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker-in-Docker

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

check_and_prepare:
  stage: check_and_prepare
  image: node:22-alpine
  before_script:
    - apk add --no-cache git
    - git config --global user.email "ci-bot@prometheus.systems"
    - git config --global user.name "CI Bot"
    - git checkout $CI_COMMIT_REF_NAME # Ensure correct branch is checked out
  script:
    - echo "Checking for changes in package.json files or missing locks"
    - |
      PACKAGE_JSON_CHANGED=false
      LOCKS_MISSING=false

      # Check if package.json files have changed
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -qE "frontend/package.json|backend/package.json"; then
        echo "package.json files have changed."
        PACKAGE_JSON_CHANGED=true
      fi

      # Check if package-lock.json files are missing
      if [ ! -f frontend/package-lock.json ] || [ ! -f backend/package-lock.json ]; then
        echo "package-lock.json files are missing."
        LOCKS_MISSING=true
      fi

      # If either condition is true, proceed with clean install
      if [ "$PACKAGE_JSON_CHANGED" = true ] || [ "$LOCKS_MISSING" = true ]; then
        echo "Condition met. Performing clean install."

        # Clean and install frontend
        rm -rf frontend/node_modules frontend/package-lock.json
        cd frontend
        npm install
        cd ..

        # Clean and install backend
        rm -rf backend/node_modules backend/package-lock.json
        cd backend
        npm install
        cd ..

        # Commit new package-lock.json files
        git add frontend/package-lock.json backend/package-lock.json
        git commit -m "Regenerate package-lock.json files [ci skip]" || echo "No changes to commit"
        git push "${CI_REPOSITORY_URL}" $CI_COMMIT_REF_NAME

        # Exit pipeline
        echo "New package-lock.json files committed. Exiting pipeline."
        exit 0
      else
        echo "No changes detected. Proceeding with the pipeline."
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'



# Step 2: Testing
test:
  stage: test
  image: node:22-alpine
  script:
    - echo "Checking for changes in frontend/package.json"
    - |
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q "frontend/package.json"; then
        echo "frontend/package.json has changed. Running npm install..."
        cd frontend
        npm install
      else
        echo "frontend/package.json has not changed. Running npm ci..."
        cd frontend
        npm ci
      fi
    - npm test
    - echo "Checking for changes in backend/package.json"
    - |
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q "backend/package.json"; then
        echo "backend/package.json has changed. Running npm install..."
        cd ../backend
        npm install
      else
        echo "backend/package.json has not changed. Running npm ci..."
        cd ../backend
        npm ci
      fi
    - npm test
  only:
    - develop
    - main

# Step 3: Build
build:
  stage: build
  image: docker:24.0
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker-in-Docker
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo "Building Docker images"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "develop" ]]; then
        TAG="$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")-dev"
      else
        TAG="$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")"
      fi
      export VERSION=$TAG
    - if [[ $CI_COMMIT_BRANCH == "develop" ]]; then docker build -t ${FRONTEND_IMAGE_NAME}:${VERSION} -f ./Dockerfile-Frontend.dev .; else docker build -t ${FRONTEND_IMAGE_NAME}:${VERSION} -f ./Dockerfile-Frontend .; fi
    - if [[ $CI_COMMIT_BRANCH == "develop" ]]; then docker build -t ${BACKEND_IMAGE_NAME}:${VERSION} -f ./Dockerfile-Backend.dev .; else docker build -t ${BACKEND_IMAGE_NAME}:${VERSION} -f ./Dockerfile-Backend .; fi
    - docker push ${FRONTEND_IMAGE_NAME}:${VERSION}
    - docker push ${BACKEND_IMAGE_NAME}:${VERSION}
  only:
    - develop
    - main
    - tags

# Step 4: Deploy
deploy:
  stage: deploy
  image: docker:24.0
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker-in-Docker
  before_script:
    - echo "Setting up SSH credentials"
    - mkdir -p ~/.ssh
    - echo "$HOST_PRIVATE_KEY_B64" | base64 --decode > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$HOST_URL" >> ~/.ssh/known_hosts
  script:
    - echo "Sending secrets to VPS and deploying application"
    - |
      ssh ${VPS_USER}@${HOST_URL} << EOF
        mkdir -p /home/ubuntu/shared-notes
        echo "Decoding secrets and writing to file"
        echo "POSTGRES_CONNECTION_STRING_DEV=\$(echo $POSTGRES_CONNECTION_STRING_DEV_B64 | base64 --decode)" >> /home/ubuntu/shared-notes/secrets.env
        echo "POSTGRES_CONNECTION_STRING_PROD=\$(echo $POSTGRES_CONNECTION_STRING_PROD_B64 | base64 --decode)" >> /home/ubuntu/shared-notes/secrets.env
        chmod 600 /home/ubuntu/shared-notes/secrets.env

        echo "Pulling Docker images"
        docker pull ${FRONTEND_IMAGE_NAME}:${VERSION}
        docker pull ${BACKEND_IMAGE_NAME}:${VERSION}

        echo "Deploying containers with Docker Compose"
        docker-compose -f docker-compose.yml up -d --remove-orphans
      EOF
  only:
    - main
