reset_repository:
  stage: check_and_prepare
  image: alpine/git  # Lightweight image with Git installed
  before_script:
    - apk add --no-cache bash
  script:
    - echo "Resetting repository..."
    - cd ..
    - rm -rf $CI_PROJECT_DIR  # Remove the current repository
    - git clone $CI_REPOSITORY_URL $CI_PROJECT_DIR  # Re-clone the repository
    - cd $CI_PROJECT_DIR  # Move back into the repository
    - git checkout $CI_COMMIT_REF_NAME  # Ensure you’re on the branch that triggered the job
    - echo "Repository has been reset."
