stages:
  - reset

reset_repository:
  stage: reset
  image: alpine/git  # Lightweight Git image
  before_script:
    - apk add --no-cache bash  # Ensure the shell environment is available
  script:
    - echo "Resetting repository..."
    - cd ..
    - rm -rf $CI_PROJECT_DIR  # Remove the repository
    - git clone $CI_REPOSITORY_URL $CI_PROJECT_DIR  # Re-clone the repository
    - cd $CI_PROJECT_DIR
    - git checkout $CI_COMMIT_REF_NAME  # Check out the correct branch or commit
    - echo "Repository has been reset successfully."
