# Dockerfile.dev
FROM node:22-alpine


ARG repo_path=/home/node/
ARG build_path=frontend/
ARG shared_path=shared/

WORKDIR ${repo_path}

# Copy package files and install dependencies
COPY ${frontend_path}package*.json ./${frontend_path}
COPY ${shared_path}package*.json ./${shared_path}
COPY package*.json ./
RUN npm install

# Copy all source code
COPY ${frontend_path} ./${frontend_path}

# Copy shared resources
COPY ${shared_path} ./${shared_path}

# Expose the port the dev server runs on
EXPOSE 3000

# Run in development mode
CMD ["npm", "run", "dev", "test"]
