# Backend Dockerfile.dev

# Use a Node.js image with TypeScript support
FROM node:22-alpine

ARG repo_path=/home/node/
ARG build_path=backend/
ARG shared_path=shared/

# Copy package files and install shared dependencies
WORKDIR ${repo_path}${shared_path}
COPY ${shared_path}package*.json ./
RUN npm install

# Copy package files and install backend dependencies
WORKDIR ${repo_path}${build_path}
COPY ${build_path}package*.json ./
RUN npm install

# Copy all source code
COPY ${build_path} .

# Copy shared resources
COPY ${shared_path} ${repo_path}${shared_path}

# Expose port 5000 for the backend server
EXPOSE 5000

# Start the backend server in development mode with nodemon
CMD ["npm", "run", "dev", "test"]

