# Dockerfile

# Stage 1: Build the application
FROM node:22-alpine AS build

ARG repo_path=/home/node/
ARG frontend_path=backend/
ARG shared_path=shared/

WORKDIR ${repo_path}

# Copy package files and install dependencies
COPY ${frontend_path}package*.json ./${frontend_path}
COPY ${shared_path}package*.json ./${shared_path}
COPY package*.json .
RUN npm install
RUN npm list

# Copy all source code
COPY ${frontend_path} ./${frontend_path}

# Copy shared resources
COPY ${shared_path} ./${shared_path}

RUN npm run build-frontend  # Assumes build files are generated in /app/dist or /app/build

# Stage 2: Serve the built app with Nginx
FROM nginx:alpine

ARG repo_path=/home/node/
ARG frontend_path=frontend/
ARG shared_path=shared/

# Copy built files from the previous stage
COPY --from=build ${repo_path}${frontend_path}/dist /usr/share/nginx/html

# Copy a custom Nginx configuration file to handle SPA routing (optional)
COPY ${frontend_path}nginx.conf /etc/nginx/conf.d/default.conf

# Expose Nginx's default HTTP port
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
