# Backend Dockerfile.dev

# Use a Node.js image with TypeScript support
FROM node:22-alpine

ARG repo_path=/home/node/
ARG backend_path=backend/
ARG shared_path=shared/

WORKDIR ${repo_path}

# Copy package files and install dependencies
COPY ${backend_path}package*.json ./${backend_path}
COPY ${shared_path}package*.json ./${shared_path}
COPY package*.json ./
RUN npm install

# Copy all source code
COPY ${backend_path} ./${backend_path}

# Copy shared resources
COPY ${shared_path} ./${shared_path}

# Expose port 5000 for the backend server
EXPOSE 5000

# Start the backend server in development mode with nodemon
CMD ["npm", "run", "dev-backend", "test"]

