# Backend Dockerfile

# Use a Node.js image
FROM node:22-alpine

ARG repo_path=/home/node/
ARG build_path=backend/
ARG shared_path=shared/

WORKDIR ${repo_path}${build_path}

# Copy package files and install dependencies
COPY ${build_path}package*.json ./
RUN npm install

# Copy all source code
COPY ${build_path} .

# Copy shared resources
COPY ${shared_path} ${repo_path}${shared_path}

RUN npm run build  # Make sure theres a "build" script in package.json like "tsc"

# Expose port 5000 for the backend
EXPOSE 5000

# Start the backend server
CMD ["npm", "start"]
