# Backend Dockerfile

# Use a Node.js image
FROM node:18-alpine

# Set the working directory and copy backend code
WORKDIR /server
COPY package*.json ./
COPY . .

# Install dependencies
RUN npm install

# Expose port 5000 for the backend
EXPOSE 5000

# Start the backend server
CMD ["npm", "start"]
